### ISSUE TITLE
Conntected error IA6B

### ISSUE THREAD

**Issue by tn2009** [Cleric-K/FlySkyRxFirmwareRssiMod#10]

**Comment by Cleric-K** [comment]
Changing the Readout protection erases the flash I think. That is, there's no point in the ROP if you can just flip the bit and read it out. So it allows to the remove the protection but it also erases the flash memory.

You can try Connect Under Reset.
Locate the Reset pad near the Data and Clock.
You'll need some way to supply 0V (GND) to the RST pad by hand (so that you can remove it at anytime).
1. Restart both STLink Util and replug the stlink usb just to make sure you are starting clean.
2. Open the settings in Stlink util and change connection mode to Connect Under Reset. Do not connect yet.
3. Hold 0V at the RST pad. While you are holding it you are keeping the MCU in reset state (but still it allows some special communication over the debug pads).
4. Press connect in stlink util.
5. Initially nothing happens, then release the GND from the RST pad. It should connect.
6. Flash the firmware normally.

**Comment by tn2009** [comment]
Recovered. Everything works. Thanks! Why is RSSI always 98 percent instead of 99. Is this how it should be? INav 2.3 firmware

**Comment by Cleric-K** [comment]
What is the channel value when looking in the receiver tab of the configurator (in the 1000-2000 range)?

**Comment by tn2009** [comment]
1990

**Comment by Cleric-K** [comment]
Well, +/- few percent is in about the margin or error, so I wouldn't be concerned.
